include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    - camel_case_types
    - require_trailing_commas
    - prefer_const_constructors
    - prefer_const_declarations
    - public_member_api_docs
