name: auto_retry
description: The AutoRetry plugin for Televerse automatically retries failed API requests, handling rate limits and server errors to improve your bot's reliability and uptime.
version: 1.0.6
repository: https://github.com/xooniverse/auto_retry
homepage: https://televerse.xooniverse.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  televerse: ^1.23.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

funding:
  - https://buymeacoffee.com/heysreelal

topics:
  - televerse
  - telegram-bot
  - plugin
  - telegram
